name: ImmigQuant
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - requests
  - beautifulsoup4
  - matplotlib
  - seaborn
  - plotly
  - dash
  - pip:
      - streamlit
      - streamlit-aggrid

